<?php
abstract class DaysOfWeek
{
    const instaToken = "IGQVJYMGtJdGg2djBibWxjUm9famRyTExoWThfdElGXzMxMHM0amZAJaFpxd0pidVhuN3k2UDdpNVJ5SHplc1g3VXc0T3FXTVFkSTFmU3JocWNkaEU4LTBVSjhMamFINkJfM2NjcEVYTkFJQ09VSmE4ZAAZDZD";
}